global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka1'
    static_configs:
      - targets: ['kafka1:9406']

  - job_name: 'kafka2'
    static_configs:
      - targets: ['kafka2:9406']

  - job_name: 'kafka3'
    static_configs:
      - targets: ['kafka3:9406']

  - job_name: 'kafka-connect1'
    static_configs:
      - targets: ['kafka-connect1:9407']

  - job_name: 'kafka-connect2'
    static_configs:
      - targets: ['kafka-connect2:9407']

  - job_name: 'kafka-connect3'
    static_configs:
      - targets: ['kafka-connect3:9407']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
