global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9406']

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:9407']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
