{
 "title": "Kafka connect data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outgoing bytes rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{job=~\"kafka-connect.\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming bytes rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{job=~\"kafka-connect.\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_coordinator_metrics_rebalance_latency_avg{job=~\"kafka-connect.\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka connect UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"kafka-connect.\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}