{
 "title": "Kafka data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"kafka.\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_meanrate{topic=\"api-data\", name=\"BytesOutPerSec\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes in per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_meanrate{topic=\"api-data\", name=\"BytesInPerSec\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}