{
 "title": "Météo d'Amiens",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Température courante",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température maximal ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "weather_elevation_meters{location=\"amiens\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Direction du vent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_winddirection_degrees{location=\"amiens\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vitesse du vent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "weather_windspeed_kmh{location=\"amiens\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}