version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:

  ##################
  # KAFKA SERVICES #
  ##################

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    environment:
      # Kafka settings
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # JMX settings for monitoring
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9406:/opt/jmx_exporter/kafka-jmx-exporter.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=kafka
    ports:
      # Expose Kafka on port 9092
      - "9092:9092"
      # JMX ports for monitoring
      - "9999:9999"
      - "9406:9406"
    volumes:
      # JMX Exporter files
      - "${PWD}/jmxexporter/jmx_prometheus_javaagent-1.3.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar"
      - "${PWD}/jmxexporter/config.yml:/opt/jmx_exporter/kafka-jmx-exporter.yml"
    networks:
      - kafka-net

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.9.1
    depends_on:
      - kafka
    environment:
      # Kafka connect settings
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: "compose-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "docker-connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "docker-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "docker-connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
      # JMX settings for monitoring
      CONNECT_JMX_PORT: 9998
      CONNECT_JMX_HOSTNAME: kafka-connect
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9407:/opt/jmx_exporter/kafka-connect-jmx-exporter.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=kafka-connect
    ports:
      # Expose Kafka Connect REST API on port 8083
      - "8083:8083"
      # JMX port for monitoring
      - "9998:9998"
      - "9407:9407"
    volumes:
      # kafka connect plugins
      - "${PWD}/kafka-connect-plugins/confluentinc-kafka-connect-http-source-1.0.0:/usr/share/java/confluentinc-kafka-connect-http-source"
      # JMX Exporter files
      - "${PWD}/jmxexporter/jmx_prometheus_javaagent-1.3.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar"
      - "${PWD}/jmxexporter/config.yml:/opt/jmx_exporter/kafka-connect-jmx-exporter.yml"
    networks:
      - kafka-net

  kafka-client:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - kafka
    entrypoint: ["sleep", "infinity"]  # Conteneur reste ouvert pour que tu puisses exec dedans
    networks:
      - kafka-net
  # Why this service?
  # The kafka service have JMX exporter
  # Thies means that everytime we want tu execture a kafka cli command
  # it returns an error. we can use this service to execute
  # kafka cli commands without the JMX exporter
  # the following command can be used to read api-data topic:
  # docker exec -it compose-kafka-client-1 kafka-console-consumer --bootstrap-server kafka:9092 --topic api-data --from-beginning



  ##################
  #   PROMETHEUS   #
  ##################

  prometheus:
    image: bitnami/prometheus:3.4.1
    ports:
      - "9090:9090"
    volumes:
      - "${PWD}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
    networks:
      - kafka-net

  node-exporter:
      image: bitnami/node-exporter:1.9.1
      ports:
        - "9100:9100"
      command:
      - "--collector.textfile.directory=/var/lib/node_exporter/textfile_collector"
      volumes:
        - "${PWD}/custom-metrics:/var/lib/node_exporter/textfile_collector"
      networks:
        - kafka-net



  ##################
  #  CMD LAUNCHER  #
  ##################

  ubuntu-init:
    image: ubuntu:24.04
    depends_on:
      - kafka-connect
    volumes:
      - "${PWD}/entrypoints/ubuntu-init.entrypoint.sh:/etc/ubuntu-init/entrypoint.sh"
      - "${PWD}/kafka-connect-settings/amiens-weather-http-source.json:/tmp/amiens-weather-http-source.json"
    entrypoint: ["/etc/ubuntu-init/entrypoint.sh"]
    networks:
      - kafka-net

  kafka-consumer:
    image: maven:3.9.9
    working_dir: /app
    volumes:
      - "${PWD}/java/consumer:/app"
      - "${PWD}/custom-metrics:/app/metrics"
    command: mvn compile exec:java -Dexec.mainClass="isri.kafka.Consumer"
    depends_on:
      - kafka
    networks:
      - kafka-net
