startDelaySeconds: 0             # Initial delay before the first scrape
lowercaseOutputName: true        # Convert output names to lowercase
lowercaseOutputLabelNames: true  # Convert label names to lowercase
rules:
  - pattern: ".*"                # Match all metrics

